-- Database backup created on 2025-09-16T07:41:33.469Z
-- Generated by SRPH-MIS

-- Data for table: iam_accounts
-- 111 rows

-- Data for table: assets
-- 1 rows

-- Data for table: users
-- 2 rows

-- Data for table: system_settings
-- 1 rows

-- Data for table: it_equipment
-- 1 rows

-- Data for table: activities
-- 32 rows

-- Data for table: settings
-- 1 rows

